# Generated by Django 3.2.16 on 2022-12-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amado', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default=2, max_length=300, verbose_name='description'),
            preserve_default=False,
        ),
    ]
